### ISSUE TITLE
`data/pcaCover.csv` missing

### ISSUE THREAD

**Issue by pfdamasceno** [mrazvan22/brain-coloring#1]
Hi, I'm trying to follow the steps for testing out brain-coloring. Should there be a `data/pcaCover.csv` file here somewhere? Sorry if I'm missing something obvious...

**Comment by mrazvan22** [comment]
Sorry, that was an old template which I have removed, but I forgot to update the README. The default template is now set to input/DK_template.csv . I now updated the README, run "git pull origin master" to get the latest one.

**Comment by mrazvan22** [comment]
Also see config.py for the default input file and output folder, you can change these to the desired ones.
